"""Model families and common research implementations."""

from trading_bot.models.advanced import (
    CORE_ADVANCED_ARCHITECTURES,
    AdvancedArchitecture,
    AdvancedModelProfile,
    AdvancedModelSpec,
    AdvancedScale,
    FoundationBackbone,
    FoundationModelIdentity,
    FrozenFoundationAdapter,
    ITransformerReturnModel,
    MambaReferenceReturnModel,
    PatchTSTReturnModel,
    TemporalCrossSectionalTransformerReturnModel,
    TemporalGraphReturnModel,
    VSNLSTMReturnModel,
    advanced_model_spec,
    build_advanced_model,
    profile_advanced_model,
)
from trading_bot.models.baseline_checkpoint import (
    ClassicalCheckpointError,
    ClassicalCheckpointIdentity,
    restore_classical_checkpoint,
    save_classical_checkpoint,
)
from trading_bot.models.baseline_classical import (
    ClassicalBaseline,
    ClassicalBaselineError,
    ElasticNetBaseline,
    LightGBMBaseline,
    LogisticDirectionBaseline,
    RidgeBaseline,
    XGBoostBaseline,
)
from trading_bot.models.baseline_common import (
    BaselineComplexity,
    BaselineInferenceBenchmark,
    BaselineSplit,
    BaselineTargetNames,
)
from trading_bot.models.baseline_neural import (
    BaselineMLPModel,
    CausalTransformerReturnModel,
    GRUReturnModel,
    LSTMReturnModel,
    TCNReturnModel,
)
from trading_bot.models.baseline_objectives import build_baseline_loss
from trading_bot.models.toy import (
    LinearReturnModel,
    MLPReturnModel,
    ResidualGatedReturnModel,
)

__all__ = [
    "CORE_ADVANCED_ARCHITECTURES",
    "AdvancedArchitecture",
    "AdvancedModelProfile",
    "AdvancedModelSpec",
    "AdvancedScale",
    "BaselineComplexity",
    "BaselineInferenceBenchmark",
    "BaselineMLPModel",
    "BaselineSplit",
    "BaselineTargetNames",
    "CausalTransformerReturnModel",
    "ClassicalBaseline",
    "ClassicalBaselineError",
    "ClassicalCheckpointError",
    "ClassicalCheckpointIdentity",
    "ElasticNetBaseline",
    "FoundationBackbone",
    "FoundationModelIdentity",
    "FrozenFoundationAdapter",
    "GRUReturnModel",
    "ITransformerReturnModel",
    "LSTMReturnModel",
    "LightGBMBaseline",
    "LinearReturnModel",
    "LogisticDirectionBaseline",
    "MLPReturnModel",
    "MambaReferenceReturnModel",
    "PatchTSTReturnModel",
    "ResidualGatedReturnModel",
    "RidgeBaseline",
    "TCNReturnModel",
    "TemporalCrossSectionalTransformerReturnModel",
    "TemporalGraphReturnModel",
    "VSNLSTMReturnModel",
    "XGBoostBaseline",
    "advanced_model_spec",
    "build_advanced_model",
    "build_baseline_loss",
    "profile_advanced_model",
    "restore_classical_checkpoint",
    "save_classical_checkpoint",
]
